
package org.bg.bpo.register.search;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-06-29T01:28:04.603+03:00
 * Generated source version: 2.7.16
 * 
 */
public final class BPORegisterSearch_BPOSearchServiceDefaultPort_Client {

    private static final QName SERVICE_NAME = new QName("http://bg.org/bpo/register/search/", "BPOSearchService");

    private BPORegisterSearch_BPOSearchServiceDefaultPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BPOSearchService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BPOSearchService ss = new BPOSearchService(wsdlURL, SERVICE_NAME);
        BPORegisterSearch port = ss.getBPOSearchServiceDefaultPort();  
        
        {
        System.out.println("Invoking getMarkByAppNum...");
        java.lang.String _getMarkByAppNum_appnum = "1948004655N";
        java.util.List<bg.egov.regix.patentdepartment.TradeMarkType> _getMarkByAppNum__return = port.getMarkByAppNum(_getMarkByAppNum_appnum);
        System.out.println("getMarkByAppNum.result=" + _getMarkByAppNum__return);
        System.out.println("getMarkByRegNum.id=" + _getMarkByAppNum__return.get(0).getApplicationNumber());


        }
        {
        System.out.println("Invoking getMarkByRegNum...");
        String _getMarkByRegNum_regnum = "00000556";
        java.util.List<bg.egov.regix.patentdepartment.TradeMarkType> _getMarkByRegNum__return = port.getMarkByRegNum(_getMarkByRegNum_regnum);
        System.out.println("getMarkByRegNum.result=" + _getMarkByRegNum__return);
        System.out.println("getMarkByRegNum.id=" + _getMarkByRegNum__return.get(0).getApplicationNumber());


        }
        {
        System.out.println("Invoking getMarkByOwnersName...");
        java.lang.String _getMarkByOwnersName_fname = "Linguaphone";
        java.lang.String _getMarkByOwnersName_sname = "";
        java.lang.String _getMarkByOwnersName_lname = "";
        java.util.List<bg.egov.regix.patentdepartment.TradeMarkType> _getMarkByOwnersName__return = port.getMarkByOwnersName(_getMarkByOwnersName_fname, _getMarkByOwnersName_sname, _getMarkByOwnersName_lname);
        System.out.println("getMarkByOwnersName.result=" + _getMarkByOwnersName__return);
        System.out.println("getMarkByRegNum.id=" + _getMarkByOwnersName__return.get(0).getApplicationNumber());


        }
    }

}
