package org.bg.bpo.register.search;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-06-23T12:56:05.689+03:00
 * Generated source version: 2.7.16
 * 
 */
@WebService(targetNamespace = "http://bg.org/bpo/register/search/", name = "BPORegisterSearch")
@XmlSeeAlso({bg.egov.regix.patentdepartment.ObjectFactory.class})
public interface BPORegisterSearch {

    @WebMethod(action = "http://bg.org/bpo/register/search/getMarkByRegNum")
    @RequestWrapper(localName = "getMarkByRegNum", targetNamespace = "http://egov.bg/RegiX/PatentDepartment", className = "bg.egov.regix.patentdepartment.GetMarkByRegNumType")
    @ResponseWrapper(localName = "TradeMarkDetails", targetNamespace = "http://egov.bg/RegiX/PatentDepartment", className = "bg.egov.regix.patentdepartment.TradeMarkDetailsType")
    @WebResult(name = "TradeMark", targetNamespace = "http://egov.bg/RegiX/PatentDepartment")
    public java.util.List<bg.egov.regix.patentdepartment.TradeMarkType> getMarkByRegNum(
        @WebParam(name = "regnum", targetNamespace = "http://egov.bg/RegiX/PatentDepartment")
        int regnum
    );

    @WebMethod(action = "http://bg.org/bpo/register/search/getMarksByName")
    @RequestWrapper(localName = "getMarksByName", targetNamespace = "http://egov.bg/RegiX/PatentDepartment", className = "bg.egov.regix.patentdepartment.GetMarksByNameType")
    @ResponseWrapper(localName = "TradeMarkDetails", targetNamespace = "http://egov.bg/RegiX/PatentDepartment", className = "bg.egov.regix.patentdepartment.TradeMarkDetailsType")
    @WebResult(name = "TradeMark", targetNamespace = "http://egov.bg/RegiX/PatentDepartment")
    public java.util.List<bg.egov.regix.patentdepartment.TradeMarkType> getMarksByName(
        @WebParam(name = "markname", targetNamespace = "http://egov.bg/RegiX/PatentDepartment")
        java.lang.String markname
    );

    @WebMethod(action = "http://bg.org/bpo/register/search/getMarkByOwnersName")
    @RequestWrapper(localName = "getMarkByOwnersName", targetNamespace = "http://egov.bg/RegiX/PatentDepartment", className = "bg.egov.regix.patentdepartment.GetMarkByOwnersNameType")
    @ResponseWrapper(localName = "TradeMarkDetails", targetNamespace = "http://egov.bg/RegiX/PatentDepartment", className = "bg.egov.regix.patentdepartment.TradeMarkDetailsType")
    @WebResult(name = "TradeMark", targetNamespace = "http://egov.bg/RegiX/PatentDepartment")
    public java.util.List<bg.egov.regix.patentdepartment.TradeMarkType> getMarkByOwnersName(
        @WebParam(name = "fname", targetNamespace = "http://egov.bg/RegiX/PatentDepartment")
        java.lang.String fname,
        @WebParam(name = "sname", targetNamespace = "http://egov.bg/RegiX/PatentDepartment")
        java.lang.String sname,
        @WebParam(name = "lname", targetNamespace = "http://egov.bg/RegiX/PatentDepartment")
        java.lang.String lname
    );

    @WebMethod(action = "http://bg.org/bpo/register/search/getMarkByAppNum")
    @RequestWrapper(localName = "getMarkByAppNum", targetNamespace = "http://egov.bg/RegiX/PatentDepartment", className = "bg.egov.regix.patentdepartment.GetMarkByAppNumType")
    @ResponseWrapper(localName = "TradeMarkDetails", targetNamespace = "http://egov.bg/RegiX/PatentDepartment", className = "bg.egov.regix.patentdepartment.TradeMarkDetailsType")
    @WebResult(name = "TradeMark", targetNamespace = "http://egov.bg/RegiX/PatentDepartment")
    public java.util.List<bg.egov.regix.patentdepartment.TradeMarkType> getMarkByAppNum(
        @WebParam(name = "appnum", targetNamespace = "http://egov.bg/RegiX/PatentDepartment")
        java.lang.String appnum
    );
}
