
package org.bg.bpo.register.search;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-06-23T12:56:05.573+03:00
 * Generated source version: 2.7.16
 * 
 */
public final class BPORegisterSearch_BPOSearchServiceDefaultPort_Client {

    private static final QName SERVICE_NAME = new QName("http://bg.org/bpo/register/search/", "BPOSearchService");

    private BPORegisterSearch_BPOSearchServiceDefaultPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BPOSearchService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BPOSearchService ss = new BPOSearchService(wsdlURL, SERVICE_NAME);
        BPORegisterSearch port = ss.getBPOSearchServiceDefaultPort();  
        
        {
        System.out.println("Invoking getMarkByRegNum...");
        int _getMarkByRegNum_regnum = -1776674128;
        java.util.List<bg.egov.regix.patentdepartment.TradeMarkType> _getMarkByRegNum__return = port.getMarkByRegNum(_getMarkByRegNum_regnum);
        System.out.println("getMarkByRegNum.result=" + _getMarkByRegNum__return);
        System.out.println("getMarkByRegNum.id=" + _getMarkByRegNum__return.get(0).getApplicationNumber());


        }
        {
        System.out.println("Invoking getMarksByName...");
        java.lang.String _getMarksByName_markname = "_getMarksByName_markname-433492095";
        java.util.List<bg.egov.regix.patentdepartment.TradeMarkType> _getMarksByName__return = port.getMarksByName(_getMarksByName_markname);
        System.out.println("getMarksByName.result=" + _getMarksByName__return);


        }
        {
        System.out.println("Invoking getMarkByOwnersName...");
        java.lang.String _getMarkByOwnersName_fname = "_getMarkByOwnersName_fname-1374284855";
        java.lang.String _getMarkByOwnersName_sname = "_getMarkByOwnersName_sname1762524241";
        java.lang.String _getMarkByOwnersName_lname = "_getMarkByOwnersName_lname-563443667";
        java.util.List<bg.egov.regix.patentdepartment.TradeMarkType> _getMarkByOwnersName__return = port.getMarkByOwnersName(_getMarkByOwnersName_fname, _getMarkByOwnersName_sname, _getMarkByOwnersName_lname);
        System.out.println("getMarkByOwnersName.result=" + _getMarkByOwnersName__return);


        }
        {
        System.out.println("Invoking getMarkByAppNum...");
        java.lang.String _getMarkByAppNum_appnum = "_getMarkByAppNum_appnum-838380618";
        java.util.List<bg.egov.regix.patentdepartment.TradeMarkType> _getMarkByAppNum__return = port.getMarkByAppNum(_getMarkByAppNum_appnum);
        System.out.println("getMarkByAppNum.result=" + _getMarkByAppNum__return);


        }

        System.exit(0);
    }

}
